"""Daily report (07:00 Europe/Bucharest): Markdown file + Telegram summary.

Numbers come from the freqtrade API and the journal — never invented. The
"improvement hypothesis" is advisory only and is NEVER auto-applied (spec
§6.5); it is generated by the LLM when a key is configured, otherwise a
deterministic placeholder is written.
"""

from __future__ import annotations

import logging
import os
from datetime import datetime, timedelta, timezone
from pathlib import Path

from riskguard.guard import check_breakers
from riskguard.state import load_state

from orchestrator.freqtrade_api import FreqtradeAPI
from strategist import journal
from strategist.telegram_alerts import send_alert

logger = logging.getLogger(__name__)

REPORTS_DIR = Path(os.environ.get("SANTINELA_REPORTS_DIR", "reports"))
STATE_DIR = Path(os.environ.get("SANTINELA_STATE_DIR", "user_data/riskguard_state"))


def _fmt(value, digits=2, suffix=""):
    if value is None:
        return "n/a"
    try:
        return f"{float(value):.{digits}f}{suffix}"
    except (TypeError, ValueError):
        return str(value)


def _pnl_windows(api: FreqtradeAPI) -> tuple:
    """(day_abs, day_pct, week_abs) from the /daily endpoint."""
    try:
        import requests
        resp = requests.get(f"{api.base_url}/api/v1/daily?timescale=7",
                            auth=api.auth, timeout=api.timeout)
        resp.raise_for_status()
        days = resp.json().get("data", [])
        day = days[0] if days else {}
        week_abs = sum(float(d.get("abs_profit") or 0) for d in days)
        return (day.get("abs_profit"), day.get("rel_profit"), week_abs)
    except Exception as exc:
        logger.warning("daily pnl fetch failed: %s", exc)
        return (None, None, None)


def _hypothesis(stats_md: str) -> str:
    """Advisory improvement hypothesis. LLM if available, placeholder if not."""
    if not os.environ.get("ANTHROPIC_API_KEY"):
        return ("_No ANTHROPIC_API_KEY configured — hypothesis skipped. "
                "(Advisory only; never auto-applied.)_")
    try:
        import anthropic
        client = anthropic.Anthropic(timeout=60.0, max_retries=0)
        response = client.messages.create(
            model=os.environ.get("STRATEGIST_MODEL", "claude-sonnet-4-6"),
            max_tokens=300,
            system=(
                "You review a small crypto spot trading system's daily stats. "
                "Reply with ONE testable improvement hypothesis in 2-3 plain "
                "sentences. It is advisory only and will never be auto-applied. "
                "Do not propose changing locked risk limits."
            ),
            messages=[{"role": "user", "content": stats_md}],
        )
        text = next((b.text for b in response.content if b.type == "text"), "")
        usage = response.usage
        journal.append("llm_call", {
            "purpose": "daily_report_hypothesis",
            "model": response.model,
            "input_tokens": usage.input_tokens,
            "output_tokens": usage.output_tokens,
        })
        return text.strip() or "_(empty hypothesis)_"
    except Exception as exc:
        logger.warning("hypothesis generation failed: %s", exc)
        return f"_Hypothesis generation failed ({type(exc).__name__}) — skipped._"


def generate_report(api: FreqtradeAPI | None = None, state=None,
                    now_local: datetime | None = None) -> Path:
    api = api or FreqtradeAPI()
    state = state if state is not None else load_state(STATE_DIR)
    now_local = now_local or datetime.now(timezone.utc)
    now_utc = now_local.astimezone(timezone.utc)

    profit: dict = {}
    open_trades: list = []
    equity = None
    try:
        profit = api.profit()
        open_trades = api.status()
        equity = api.equity()
    except Exception as exc:
        logger.warning("report: freqtrade API unavailable: %s", exc)

    day_abs, day_pct, week_abs = _pnl_windows(api)
    breakers = check_breakers(state, now_utc)

    cutoff = (now_utc - timedelta(hours=24)).isoformat()
    guard_events = [r for r in journal.tail("guard_event", limit=50)
                    if r.get("ts", "") >= cutoff]
    verdicts = journal.tail("verdict", limit=6)

    wins = int(profit.get("winning_trades") or 0)
    losses = int(profit.get("losing_trades") or 0)
    closed = wins + losses
    win_rate = (wins / closed * 100) if closed else None

    date_str = now_local.strftime("%Y-%m-%d")
    lines = [
        f"# Santinela daily report — {date_str}",
        "",
        f"Generated: {now_local.isoformat()} | Mode: "
        f"{os.environ.get('TRADING_MODE', 'dry')}",
        "",
        "## Account",
        f"- Equity: **{_fmt(equity)}** (HWM: {_fmt(state.hwm)}, "
        f"drawdown from HWM: "
        f"{_fmt((state.last_equity - state.hwm) / state.hwm * 100 if state.hwm else None, 2, '%')})",
        f"- PnL today: {_fmt(day_abs)} ({_fmt(day_pct if day_pct is None else float(day_pct) * 100, 2, '%')})"
        f" | PnL 7d: {_fmt(week_abs)}",
        f"- Closed trades (all time): {closed} | win rate: {_fmt(win_rate, 1, '%')}"
        f" | profit factor: {_fmt(profit.get('profit_factor'))}",
        f"- Max drawdown (bot): {_fmt((profit.get('max_drawdown') or 0) * 100, 2, '%')}",
        "",
        "## Open positions",
    ]
    if open_trades:
        for t in open_trades:
            lines.append(f"- {t.get('pair')}: {_fmt(t.get('profit_pct'), 2, '%')} "
                         f"(stake {_fmt(t.get('stake_amount'))}, "
                         f"stop {_fmt(t.get('stop_loss_abs'), 4)})")
    else:
        lines.append("- none")

    lines += [
        "",
        "## Breakers",
        f"- S6 daily-loss pause: {'ACTIVE until ' + str(breakers.s6_until) if breakers.s6_active else 'off'}",
        f"- S7 kill switch: {'KILLED' if breakers.s7_killed else 'off'}",
        f"- S8 loss-streak pause: {'ACTIVE until ' + str(breakers.s8_until) if breakers.s8_active else 'off'}",
        f"- Loss streak counter: {state.consecutive_losses}",
        f"- Guard events last 24h: "
        + (", ".join(e.get("event", "?") for e in guard_events) if guard_events else "none"),
        "",
        "## Verdict history (last 6)",
    ]
    if verdicts:
        for v in verdicts:
            c = v.get("clamped", {})
            lines.append(
                f"- {v.get('ts', '?')[:16]} `{v.get('verdict_id', '?')}`: "
                f"{c.get('regime')}/{c.get('risk_mode')}/{c.get('active_strategy')} "
                f"conf={c.get('confidence')} clamps={len(c.get('clamp_notes') or [])}"
            )
    else:
        lines.append("- none yet")

    stats_md = "\n".join(lines)
    lines += ["", "## Improvement hypothesis (advisory — never auto-applied)",
              _hypothesis(stats_md), ""]

    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    path = REPORTS_DIR / f"{date_str}.md"
    path.write_text("\n".join(lines))

    send_alert(
        f"📊 *Daily report {date_str}*\n"
        f"Equity: {_fmt(equity)} | today: {_fmt(day_abs)} | 7d: {_fmt(week_abs)}\n"
        f"Closed: {closed} | win rate: {_fmt(win_rate, 1, '%')} | "
        f"PF: {_fmt(profit.get('profit_factor'))}\n"
        f"Breakers: S6={'on' if breakers.s6_active else 'off'} "
        f"S7={'KILLED' if breakers.s7_killed else 'off'} "
        f"S8={'on' if breakers.s8_active else 'off'}\n"
        f"Full report: reports/{date_str}.md"
    )
    return path


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    print(generate_report())
